familyName: RobotoFlex
sources:
  - RobotoFlex.designspace
axisOrder:
  - GRAD
  - XOPQ
  - XTRA
  - YOPQ
  - YTAS
  - YTDE
  - YTFI
  - YTLC
  - YTUC
  - opsz
  - wdth
  - wght
  - slnt
flattenComponents: false
decomposeTransformedComponents: false